"""
Audit-Derived Regression Tests

Parameterized tests that load fixtures from tests/fixtures/audit_derived/
and verify entities + custom fields are reachable via the Acumatica REST API.

These fixtures are auto-generated by the workflow extractor from real
production audit data. They ensure that customization deploys don't break
screens/fields that users actually use.

Usage:
    pytest tests/test_audit_derived.py -v

Requires:
    ACUMATICA_URL, ACUMATICA_USERNAME, ACUMATICA_PASSWORD, ACUMATICA_TENANT
"""

import json
import os
import sys
import glob

import pytest

# Reuse AcumaticaSession from validate-publish.py
import importlib.util

_script_dir = os.path.join(os.path.dirname(__file__), "..", "scripts")
sys.path.insert(0, _script_dir)
_spec = importlib.util.spec_from_file_location(
    "validate_publish", os.path.join(_script_dir, "validate-publish.py")
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
AcumaticaSession = _mod.AcumaticaSession

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "audit_derived")


def _load_fixtures():
    """Load all JSON fixtures from the audit_derived directory."""
    fixtures = []
    if not os.path.isdir(FIXTURES_DIR):
        return fixtures
    for filepath in sorted(glob.glob(os.path.join(FIXTURES_DIR, "*.json"))):
        with open(filepath) as f:
            data = json.load(f)
        if data.get("_generated"):
            fixtures.append(data)
    return fixtures


def _fixture_ids():
    """Generate test IDs from fixture filenames."""
    if not os.path.isdir(FIXTURES_DIR):
        return []
    return [
        os.path.splitext(os.path.basename(f))[0]
        for f in sorted(glob.glob(os.path.join(FIXTURES_DIR, "*.json")))
    ]


# Skip all tests if env vars aren't set (local dev without Acumatica access)
_has_acumatica = all(
    os.environ.get(v)
    for v in ("ACUMATICA_URL", "ACUMATICA_USERNAME", "ACUMATICA_PASSWORD")
)


@pytest.fixture(scope="module")
def acumatica_session():
    """Shared Acumatica session for all tests in this module."""
    if not _has_acumatica:
        pytest.skip("ACUMATICA_URL not set")
    session = AcumaticaSession(
        url=os.environ["ACUMATICA_URL"],
        username=os.environ["ACUMATICA_USERNAME"],
        password=os.environ["ACUMATICA_PASSWORD"],
        tenant=os.environ.get("ACUMATICA_TENANT", ""),
    )
    session.login()
    yield session
    session.logout()


@pytest.mark.skipif(not _has_acumatica, reason="No Acumatica credentials")
@pytest.mark.parametrize("fixture", _load_fixtures(), ids=_fixture_ids())
def test_entity_reachable(fixture, acumatica_session):
    """Verify that each audit-observed entity is queryable without HTTP 500."""
    entity = fixture["entity"]
    result = acumatica_session.get(f"/entity/default/24.200.001/{entity}?$top=1")
    assert result.status_code != 500, (
        f"{entity} returned HTTP 500 — entity may be broken by customization"
    )


@pytest.mark.skipif(not _has_acumatica, reason="No Acumatica credentials")
@pytest.mark.parametrize("fixture", _load_fixtures(), ids=_fixture_ids())
def test_custom_fields_exist(fixture, acumatica_session):
    """Verify custom fields observed in audit data still exist in schema."""
    entity = fixture["entity"]
    custom_fields = fixture.get("custom_fields", [])
    if not custom_fields:
        pytest.skip(f"No custom fields observed for {entity}")

    # Use $adHocSchema to check field presence
    result = acumatica_session.get(
        f"/entity/default/24.200.001/{entity}/$adHocSchema?$top=1"
    )
    if result.status_code != 200:
        pytest.skip(f"Schema endpoint not available for {entity}")

    schema_text = result.text.lower()
    for field in custom_fields:
        assert field.lower() in schema_text, (
            f"Custom field {field} not found in {entity} schema — "
            f"may have been removed by customization change"
        )
