"""Audit-driven UI smoke tests — verify all user-facing screens load after deploy.

Fixtures are generated by scripts/generate_ui_fixtures.py from live
StudioBAuditTrail OData data. Each test navigates to a screen, asserts
it loads, and checks that custom fields (Usr*) are present in the DOM.

Usage:
    pytest tests/ui/test_screen_smoke.py -v

Requires:
    - tests/fixtures/ui_screens.json (generated by generate_ui_fixtures.py)
    - ACUMATICA_URL, ACUMATICA_USERNAME, ACUMATICA_PASSWORD env vars
"""

import json
import os

import pytest

from helpers import (
    navigate_to_screen,
    assert_screen_loaded,
    find_custom_fields,
)


# ── Fixture Loading ──────────────────────────────────────────────────────────

FIXTURES_PATH = os.path.join(
    os.path.dirname(__file__), "..", "fixtures", "ui_screens.json"
)


def _load_screen_fixtures():
    if not os.path.exists(FIXTURES_PATH):
        return []
    with open(FIXTURES_PATH) as f:
        return json.load(f)


def _screen_ids():
    return [f["screen_id"] for f in _load_screen_fixtures()]


_FIXTURES = _load_screen_fixtures()

# Skip everything if no fixtures or no credentials
_has_fixtures = len(_FIXTURES) > 0
_has_acumatica = all(
    os.environ.get(v)
    for v in ("ACUMATICA_URL", "ACUMATICA_USERNAME", "ACUMATICA_PASSWORD")
)


# ── Tests ────────────────────────────────────────────────────────────────────

@pytest.mark.ui
@pytest.mark.skipif(not _has_fixtures, reason="No ui_screens.json fixture file")
@pytest.mark.skipif(not _has_acumatica, reason="No Acumatica credentials")
class TestScreenSmoke:
    """Smoke tests: navigate to each audit-observed screen and verify it loads."""

    @pytest.mark.parametrize("fixture", _FIXTURES, ids=_screen_ids())
    def test_screen_loads(self, fixture, screen_page, dialog_messages):
        """Screen navigates and loads without errors."""
        screen_id = fixture["screen_id"]

        navigate_to_screen(screen_page, screen_id)
        assert_screen_loaded(screen_page, screen_id)

        # Check no error dialogs fired during navigation
        error_dialogs = [
            d for d in dialog_messages
            if "error" in d["message"].lower() or "exception" in d["message"].lower()
        ]
        assert not error_dialogs, (
            f"Screen {screen_id} ({fixture.get('screen_name', '')}) "
            f"produced error dialog(s): {[d['message'] for d in error_dialogs]}"
        )

    @pytest.mark.parametrize(
        "fixture",
        [f for f in _FIXTURES if f.get("custom_fields")],
        ids=[f["screen_id"] for f in _FIXTURES if f.get("custom_fields")],
    )
    def test_custom_fields_visible(self, fixture, screen_page):
        """Custom fields observed in audit data are present in screen DOM."""
        screen_id = fixture["screen_id"]
        custom_fields = fixture["custom_fields"]

        navigate_to_screen(screen_page, screen_id)
        assert_screen_loaded(screen_page, screen_id)

        results = find_custom_fields(screen_page, custom_fields)
        missing = [f for f, found in results.items() if not found]

        assert not missing, (
            f"Screen {screen_id} ({fixture.get('screen_name', '')}): "
            f"custom fields missing from DOM: {missing}. "
            f"These fields were observed in production audit data but are no longer "
            f"rendered — possible customization regression."
        )
